apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cheung0825

resources:
  - namespace.yml

secretGenerator:
- name: cheung0825
  env: secrets.env

# Don't add a suffix to the secret name
generatorOptions:
  disableNameSuffixHash: true
