apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- deployment.yml

resources:
- ../../base
- ingress.yml

configMapGenerator:
- name: cheung0825-config
  behavior: merge
  literals:
    - ENVIRONMENT=staging
